### ISSUE TITLE
New Method to Deposit & Stake in 1 Payable TX

### ISSUE THREAD

**Issue by mattlockyer** [near/initial-contracts#15]
Currently we have 2 methods defined to delegate stake with a validator.
```
near call my_validator deposit '{}' --accountId user1 --amount 100
near call my_validator stake '{"amount": "100000000000000000000000000"}' --accountId user1
```
https://github.com/near/initial-contracts/blob/master/staking-pool/README.md#usage

A state machine of the contract:
![image](https://user-images.githubusercontent.com/321340/81960093-452e9c80-95c5-11ea-9282-2e7709671cfc.png)

Problem:
Wallets must authorize 2 txs to stake with a validator. Often a user ("delegator") will want to stake the amount they deposit immediately.

Solution:
I propose a **new** payable method `deposit_stake` that combines the functionality of the above 2 methods into 1.

As was pointed out to me by @mikedotexe, could this be solved using batch transactions? I am unfamiliar with how these work.
https://github.com/near/near-sdk-rs/blob/add801738404a74813e74ed3e0447e9e64805c3a/examples/cross-contract-low-level/src/lib.rs#L17-L28

**Comment by evgenykuzyakov** [comment]
While it’s convenient to have this method, it’s not required. Both a contract (through promises) and the nearlib api can issue a transaction that contains 2 function call actions. The first function call is `deposit` with attached amount, the 2nd function call is `stake` with the argument of the deposited amount.

Here is nearlib API to request signing it in the wallet: https://github.com/near/near-api-js/blob/d7f0cb87ec320b723734045a4ee9d17d94574a19/src/wallet-account.ts#L96

**Comment by mattlockyer** [comment]
Thanks @evgenykuzyakov as you pointed out this can be done in the JS SDK / Web Wallet.

Here's how I achieved it for documenting this issue. Will close.

```
const { functionCall } = nearAPI.transactions
const actions = []
actions.push(functionCall('deposit', new Uint8Array(), BOATLOAD_OF_GAS, amount))
actions.push(functionCall('stake', new TextEncoder().encode(JSON.stringify({amount})), BOATLOAD_OF_GAS))
const account = walletConnection.account()
account.signAndSendTransaction(selectedContract, actions)
```
