### ISSUE TITLE
[feature request] Show the contract version/build on the blockchain

### ISSUE THREAD

**Issue by jimmy3dita** [near/initial-contracts#17]
Context: as a user, I would like to know which version of the Staking Pool contract is being used, to simplify the audit of a validator before sending my tokens.
Ideally, I should reveal this information by using a `near view` command.

Alternatively, knowing the hash/fingerprint of the deployed contract, and having an easy way to find its original source code on Github will do the job.

**Comment by evgenykuzyakov** [comment]
You can query the contract hash by doing `near state staking-pool`.
On the mainnet, staking pools hashes will have to be whitelisted by the NEAR Foundation, to avoid being able to steal/lock users deposits.
