### ISSUE TITLE
Contract out of gas error messaging

### ISSUE THREAD

**Issue by htafolla** [near/initial-contracts#34]
When the contract does not have enough gas the error that is given to the user is not descriptive enough.

ERROR:
Scheduling a call: blaze_betanet.unstake({"amount":"10000000000000000000000000000"})
Error:  GuestPanic [Error]: Smart contract panicked: panicked at &#39;The new total balance should not be less than the old total balance&#39;, src&#x2F;lib.rs:507:9

Recommended ERROR: Out of gas, send more NEAR to the contract address.

**Comment by ilblackdragon** [comment]
Ideally, contract should keep some amount on hand to pay transaction.

**Comment by evgenykuzyakov** [comment]
I plan to implement Staking pool factory, so you can't have any keys on the staking pool contracts. Which means you can't spend gas or issue a TX with fees from the account of the contract.
