### ISSUE TITLE
Contract Owner can Steal Funds from the Pool

### ISSUE THREAD

**Issue by jimmy3dita** [near/initial-contracts#9]
This issue is related to PR https://github.com/near/initial-contracts/pull/8

Sequence of events:
1. c1.nearkat deploys the staking pool contract on Betanet
2. nearkat deposit and stake 80,000 tokens to c1.nearkat
3. c1.nearkat becomes validator and generates rewards
4. c1.nearkat shuts down the node and gets kicked out from validators
5. c1.nearkat now owns 100% of the unstaked balance, and can transfer it

Proofs:
- transaction [G1sm9s8iJe7v5AyTkH4ZjWgeNfLnBrRhkHUNeNUwfC3H](https://explorer.betanet.near.org/transactions/G1sm9s8iJe7v5AyTkH4ZjWgeNfLnBrRhkHUNeNUwfC3H) 

near-shell output:
```
$ near send c1.nearkat nearkat.betanet 80300
Using options: {
  networkId: 'betanet',
  nodeUrl: 'https://rpc.betanet.nearprotocol.com',
  contractName: undefined,
  walletUrl: 'https://wallet.betanet.nearprotocol.com',
  helperUrl: 'https://helper.betanet.nearprotocol.com',
  sender: 'c1.nearkat',
  receiver: 'nearkat.betanet',
  amount: '80300',
  initialBalance: null
}
Sending 80300 NEAR to nearkat.betanet from c1.nearkat
{
  status: { SuccessValue: '' },
  transaction: {
    signer_id: 'c1.nearkat',
    public_key: 'ed25519:BXPywqpaPC8pH9Zexdh2B1S6SsXug7kfp2jykEtRA3dg',
    nonce: 4,
    receiver_id: 'nearkat.betanet',
    actions: [ { Transfer: { deposit: '80300000000000000000000000000' } } ],
    signature: 'ed25519:3hUtE1ko6SekVETz46CUQsJCRw5w2WtjKTENUcJpACyYKqYJ9rm6FA2Nyz5ngeCt3Dxi4NWpHpQpbehX9U3aL75z',
    hash: 'G1sm9s8iJe7v5AyTkH4ZjWgeNfLnBrRhkHUNeNUwfC3H'
  },
  transaction_outcome: {
    proof: [],
    block_hash: '963FRbjDXF7TourieWBUAU96Veg3FxTccY5q4nM9r6av',
    id: 'G1sm9s8iJe7v5AyTkH4ZjWgeNfLnBrRhkHUNeNUwfC3H',
    outcome: {
      logs: [],
      receipt_ids: [ 'HvSatv2paC86AeLrGCw1BAZotmkto1SD9cMZiiLZkYxT' ],
      gas_burnt: 937144500000,
      status: {
        SuccessReceiptId: 'HvSatv2paC86AeLrGCw1BAZotmkto1SD9cMZiiLZkYxT'
      }
    }
  },
  receipts_outcome: [
    {
      proof: [],
      block_hash: 'AauckaMCxTcJfm1hLtEopewgFyPypk52i5drodnevHvo',
      id: 'HvSatv2paC86AeLrGCw1BAZotmkto1SD9cMZiiLZkYxT',
      outcome: {
        logs: [],
        receipt_ids: [],
        gas_burnt: 937144500000,
        status: { SuccessValue: '' }
      }
    }
  ]
}
```

**Comment by evgenykuzyakov** [comment]
It's not a bug. You've used a full access key on `c1.nearkat` which should never be the case. You should never have a staking pool with any access keys on it. 

It can be achieved using the following:
- *Option 1*. When creating the staking pool account, deploy the staking pool contact in the same transaction.
- *Option 2*. Delete all access keys once the contract is deploys. See https://explorer.betanet.near.org/accounts/unknown.test

Explorer marks such accounts as `Locked`. 

To make sure the staking pool is legit, you need to check the following:
- Check contract hash:
```bash
env NODE_ENV=betanet near state unknown.test
```

Should result in something like:
```
Account unknown.test
{
  amount: '714032481516524361040391799',
  locked: '166739916044203650496429261441',
  code_hash: 'DpywzzTNLvpUExfMg8x6yUPuNzEXjQ22D5MpnpKxQunK',
  storage_usage: 250033,
  storage_paid_at: 0,
  block_height: 4667820,
  block_hash: 'GKTiTGqQL4W3RJdh1sCiQJ68TPLZ6UaBZevoDxczttAF',
  formattedAmount: '714.032481516524361040391799'
}
```   
The contract hash is `DpywzzTNLvpUExfMg8x6yUPuNzEXjQ22D5MpnpKxQunK`. We need to make contract compilations deterministic, so you can have a way to compare hash.

- Check access keys:
```bash
env NODE_ENV=betanet near keys unknown.test
```
The results is:
```
Keys for account unknown.test
[]
```

But in your case the keys result in the following, which makes it not secure.
```
Keys for account c1.nearkat
[
  {
    public_key: 'ed25519:BXPywqpaPC8pH9Zexdh2B1S6SsXug7kfp2jykEtRA3dg',
    access_key: { nonce: 4, permission: 'FullAccess' }
  }
]
```
